### ISSUE TITLE
Why a Licence ?

### ISSUE THREAD

**Issue by patrickpoirier51** [neilyoung/t265pose#1]
Hello Neil,

After reading your latest update here: https://github.com/IntelRealSense/librealsense/issues/5756

I got interested by your project and looking at the installation process, I see we need to download a 14 days licence.

Please explain why I need a licence to run your application, I dont get it ...

**Comment by neilyoung** [comment]
Hi Patrick,

well, the python code is obfuscated, that's why the license. I'm still undecided, what to do with it, but I also didn't want to give all away :) I have no problem to give you a license until the end of the days, just drop me a mail :)

**Comment by patrickpoirier51** [comment]
OK thanks for the offer,  please let us know if you decide to open the code so we may  collaborate somehow.
