### ISSUE TITLE
Pytransform Error: Marshal loads failed when running pose_main.py

### ISSUE THREAD

**Issue by RaphyStark** [neilyoung/t265pose#3]
Hi and thank you for your work.

I followed your instructions but when I try to install the requirements, it tells me that it can't find the correct librairies versions :
`ERROR: Could not find a version that satisfies the requirement ntplib==0.3.3 (from versions: 0.3.4, 0.4.0)
ERROR: No matching distribution found for ntplib==0.3.3`
So I changed the required version to 0.3.4 in the script, and here it says : 
`ERROR: Could not find a version that satisfies the requirement pyrealsense2==2.32.1.1299 (from versions: 2.42.0.2924, 2.43.0.3018, 2.44.0.3073, 2.45.0.3217, 2.45.0.3276, 2.45.0.3277, 2.45.0.3278, 2.47.0.3313, 2.48.0.3381, 2.49.0.3474, 2.50.0.3812)
ERROR: No matching distribution found for pyrealsense2==2.32.1.1299`
I then changed to 2.50.0.3812 and it works fine.

But when I run the /usr/local/bin/python3.9 -O -u pose_main.py -ll DEBUG command :
`Pytransform Error: Marshal loads failed when running /home/raphael/pose-0.6.0/pose_main.py `

Do you have a solution ?

Thanks for considering my request.
Raphaël.

**Comment by neilyoung** [comment]
Hi Raphaël,

Sorry for all the mess. This is a pretty old project, I recall, I got it out of the mist last year the last time for a check. Yeah, time flies and dependencies are disappearing in the history, so this is one thing, but you could solve it (we'll see, how it will work)

The runtime error is easy to explain: I was using a Python obfuscator that time (PyArmor), and I also had to learn, that this way of obfuscation very much depends on the Python interpreter version for which it is tailored. As you can see I have versions for 3.5, 3.6 and 3.7, which were on vogue that time. Not 3.9. So if possible, make you an environment with a major/minor, which matches (if possible). If not, well I would have to exhume the stuff and try to roll a 3.9 version, which also still works :)

Such gists are aged the moment you commit them, that's life :) I recall I put all the code into a self printed box, self-powered and driven by a PI 3A+ and forgot about. Interestingly there was never much interest on it. I'm surprised that the camera is still available.

Latest doc is here https://neilyoung.serveblog.net/

And here we have the DIY prototoype:

![image](https://user-images.githubusercontent.com/731020/177913263-b311051c-5bc1-4b99-adc8-6a2b807e6d3e.png)

![image](https://user-images.githubusercontent.com/731020/177913375-bc4db69f-1a94-4553-a999-ec31d10dad09.png)

The idea was to hand it out like so for tests...

Let me know how it goes.

**Comment by RaphyStark** [comment]
Hi neilyoung and thank you for your answer.
I wasn't expecting one so quickly for a 2 years old project...

I don't think that the camera is actually still available, I'm working on a project which started a few years ago.

For the python error, yeah, it makes sense now.
Don't worry, I'm going to try with the 3.7 version.

I came across your project by chance, while looking for how to save the SLAM created by the T265 :
https://github.com/IntelRealSense/librealsense/issues/5909

I keep you in touch.

**Comment by RaphyStark** [comment]
So now with a Python 3.6.

So now I extracted the python 3.6 version of your code, I copied the licence file in the correct directory and ran :
`$ /usr/bin/python3.6 -m pip install -r requirements.txt`

And there is says something very long which finishes by :
`    RuntimeError: Python version >= 3.8 required.
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-67dnb76z/transformations/`

**Comment by neilyoung** [comment]
But you are just installing requirements here. So it seems that some of the updated requirements needs to have Python3.8, or?

**Comment by RaphyStark** [comment]
True but is it ok to use 3.8 for your 3.6 version ?

Let me test...

**Comment by neilyoung** [comment]
No. The problem with PyArmor is that the minor version must match. For 3.6 you have to use 3.6, for .7 .7 and so on

**Comment by RaphyStark** [comment]
Hum... sorry but I don't get it...
When I test with 3.6, it says that I have to use 3.8.
But you say > it seems that some of the updated requirements needs to have Python3.8

So what should I do ?

**Comment by neilyoung** [comment]
The armored scripts need to be run under the same Python version which was ised for obfuscation. 

If you resolve dependencies pyarmor is not involved. Forme it looks as if one or more of the requirements need 3.8 now. 

I’m roaming. Will check options later

**Comment by RaphyStark** [comment]
Alright, thanks for your inputs.

Keep me updated please, your work is really interesting.

**Comment by neilyoung** [comment]
https://github.com/neilyoung/t265pose/releases/tag/v.1.0.0

The web app is integrated, so after start open your browser at "http://localhost:4000". If for some reasons secure is required, use neilyoung.serverblog.net.

Let me know. Should be working under Py 3.8 Tested on Ubuntu 20.04 only.

**Comment by RaphyStark** [comment]
Hi neilyoung, thank you again !
I will test it as soon as I can, and tell you how things goes :)
